### ISSUE TITLE
Client upgrade steps missing

### ISSUE THREAD

**Issue by janette** [GetDKAN/dkan_starter#473]
## Description
The **config/overrides.make** and **config/custom.make** files were not run on the 1.14 upgrades, need to run `ahoy build remake` to get those items into the build.

- perhaps only need `ahoy custom post-build` on an upgrade...?

**Comment by dafeder** [comment]
@janette I think you have a better sense of what needs to happen here - want to create a PR for this and I'll review?

**Comment by erogray** [comment]
No longer relevant
