### ISSUE TITLE
DKAN Tools

### ISSUE THREAD

**Issue by fmizzell** [GetDKAN/dkan_starter#497]
DKAN Starter contains lots of useful tools:

1. A fully built DKAN with Drupal
2. An set of docker containers to easily get DKAN running locally
3. A way to modify and isolate modifications to Drupal, DKAN, and other parts of the tooling
4. Deployment tools to work with multiple environments
5. Helper tools to get non-DKAN starter installations of DKAN working with DKAN Starter
6. And more.

All of this tooling has caused DKAN Starter to become complex and hard to maintain. Also, it would be great to allow anyone to use some or all of the tooling in accordance with their needs. Finally, we want to separate the tooling from the code, this should allow us to evolve the tooling independent of a specific version of DKAN or Drupal.

Reorganizing and revamping all of DKAN Starter would be a huge task so I will propose and MVP that hopefully satisfies most of the most common use cases and creates a framework to continue to evolve the tooling until we become as close as necessary to feature completeness.

**Initial Goals**

1.  Isolate the tooling. We would like DKAN starter to be a tool you use, and not one that becomes the base of your site.
2. Clearly separate the different types of tools. Initially we would like the following to be possible:

- [x] Get DKAN, Drupal, and connect them
- [x] Allow customization of DKAN and Drupal while keeping those isolated
- [x] Synchronizing a local development environment with another environment (Database and files).
- [x] Create an installer

Each of this goals can have many layers. As things progress we can go into more detail, and decide which are part of the MVP, and which we will push to later development.

**Comment by erogray** [comment]
Removed documentation checkpoint in favor of https://github.com/GetDKAN/dkan/issues/2511 and separate documentation ticket
