### ISSUE TITLE
Update acquia_purge to 7.x-1.4-beta2

### ISSUE THREAD

**Issue by janette** [GetDKAN/dkan_starter#506]
https://www.drupal.org/project/acquia_purge/issues/2155319
New version supports clearing wildcard URL's

- [ ] Update build.make with **acquia_purge** version 7.x-1.4-beta2
- [ ] Remove **ape** from features master (keep it in build.make for now, we will just keep it disabled by default)
- [ ] Add hook update to clear out ape config from db if not enabled
- [ ] Update default config

## Acceptance Criteria
Cache is cleared when content changes.

**Comment by acouch** [comment]
I created a dupe. Closing that one: https://github.com/NuCivic/dkan_management/issues/85

**Comment by erogray** [comment]
Probably destined for 1.15.2

**Comment by dafeder** [comment]
Reopening the management ticket, closing this one as dkan_starter is being retired.
