### ISSUE TITLE
overrides.php script not working properly

### ISSUE THREAD

**Issue by loziju** [GetDKAN/dkan_starter#507]
## Description
>overrides.make is supposed to list down module versions we want to use or patches to apply against the modules defined in dkan profile (drupal-org.make). However, instead of using the version in overrides.make, overrides.php uses the version in drupal-org.make. 

## Steps to Reproduce
>1.  Say we want to use a different version compared to the ones defined in dkan profile (drupal-org.make). Let's take uuid for example. uuid 1.1 is already updated in dkan 1.15.2 but not in dkan_starter 1.15.1.1. So in dkan_starter 1.15.1.1, which is using dkan 1.15.1, uuid version is still at 1.0.
>2.  Add the following in overrides.make
```
---
api: '2'
core: 7.x
projects:
  uuid:
    version: '1.1'
```
>3.  Run `drush php-script .ahoy/site/.scripts/overrides.php`
>4.  Observe `overriden_make.make`. Notice that uuid version used is 1.0 instead of 1.1.

## Acceptance Criteria
>Version defined in overrides.make should take precedent.

## Subtasks
>Add a list of things that need to be done to accomplish the Acceptance Criteria.

- [x] check the pull request

## Results
>When the work is complete, write the outcomes of the work. Was the acceptance criteria met? Any new documentation? Any follow up tickets created?

**Comment by acouch** [comment]
I pulled this in. Thanks.
